import test from 'node:test';
import assert from 'node:assert/strict';
import { KEY, newGame } from '../public/game.js';

test('app controls preserve a live match through pause, substitution, reload and final report',async t=>{
  // Small DOM adapter tests app event wiring; this is not a visual browser test.
  const handlers={},storage=new Map([[KEY,JSON.stringify(newGame('PSV'))]]);
  const fields={'#sub-out':{value:''},'#sub-in':{value:''}};
  const app={innerHTML:'',addEventListener(type,handler){handlers[type]=handler;}};
  const previous={document:globalThis.document,localStorage:globalThis.localStorage,setInterval:globalThis.setInterval,clearInterval:globalThis.clearInterval};
  let tick=null;
  globalThis.document={querySelector(selector){return selector==='#app'?app:fields[selector];}};
  globalThis.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};
  globalThis.setInterval=fn=>{tick=fn;return 1;};
  globalThis.clearInterval=()=>{tick=null;};
  t.after(()=>Object.assign(globalThis,previous));
  const click=dataset=>handlers.click({target:{closest:()=>({dataset,disabled:false})}});
  const state=()=>JSON.parse(storage.get(KEY));
  await import('../public/app.js?ui-test');
  click({tab:'squad'});
  assert.match(app.innerHTML,/Aanvoerder & wisselbank/);
  assert.equal((app.innerHTML.match(/data-bench=/g)||[]).length,7);
  click({tab:'overview'});click({action:'play'});
  assert.match(app.innerHTML,/AFTRAP/);
  assert.equal(state().pending.minute,0);
  click({action:'resume'});
  for(let i=0;i<25;i++)tick();
  click({action:'pause'});
  assert.equal(state().pending.minute,25);
  const oldCaptain=state().pending.captainId;
  fields['#sub-out'].value=oldCaptain;fields['#sub-in'].value=state().pending.bench[0];
  click({action:'sub'});
  assert.equal(state().pending.subs,1);
  assert.match(app.innerHTML,/Wissel toegepast!/);
  click({action:'save-close'});assert.doesNotMatch(app.innerHTML,/role="dialog"/);
  await import('../public/app.js?ui-reload');
  assert.match(app.innerHTML,/25'/);assert.match(app.innerHTML,/HERVATTEN/);
  assert.equal(state().pending.subs,1);
  click({action:'resume'});
  while(tick)tick();
  assert.equal(state().pending.minute,45);assert.match(app.innerHTML,/START TWEEDE HELFT/);
  click({action:'resume'});
  while(tick)tick();
  assert.equal(state().pending,null);assert.equal(state().round,1);
  assert.match(app.innerHTML,/FULL TIME/);assert.match(app.innerHTML,/Passnauwkeurigheid/);
  const credits=state().credits;
  click({action:'close'});assert.doesNotMatch(app.innerHTML,/role="dialog"/);
  click({action:'report'});assert.match(app.innerHTML,/FULL TIME/);
  assert.equal(state().credits,credits);
});
